### ISSUE TITLE
Bower missing

### ISSUE THREAD

**Issue by Severino** [scaffold-harmony/generator-scaffold-harmony#1]
Hey I just tried to install the project
and it's the first time I encounter yoman.

It should install all the dependencies for me, right?

There is a bower dependency that is not created nor mentioned in the readme.md.

```
...
added 2316 packages from 1297 contributors and audited 2318 packages in 49.336s
found 30 vulnerabilities (16 low, 10 moderate, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Could not finish installation. 
Please install bower with npm install -g bower and try again. 
If bower is already installed, try running the following command manually: bower install

```

**Comment by touhonoob** [comment]
Hi @Severino Thanks for trying out!
I will make some updates over the weekend. Stay tuned

**Comment by touhonoob** [comment]
@Severino Just published the latest updates. Checkout the demo videos here:

- Intro: https://youtu.be/RThMOFCN-0M
- Auto-reload: https://youtu.be/2iEv3VrNLjA

**Comment by Severino** [comment]
I tried, but I have forgotten to update the yo package and had same results. Will try at end of the week :) will have a shout out to other community members for testing.
